<?php

namespace Train\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntierRepository extends EntityRepository
{
}
