train_core:
    resource: "@TrainCoreBundle/Resources/config/routing.yml"
    prefix:   /

bde_showcase:
    resource: "@BDEShowcaseBundle/Resources/config/routing.yml"
    prefix:   /

bde_event:
    resource: "@BDEEventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: TrainUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout